DATASET:
  NAME: BI-Matrix-V2
  TRAIN_FEATURE_FILE: 'data/v2/hb_train_feature.csv'
  TRAIN_PROB_FILE: 'data/v2/hb_train_truth.csv'
  TEST_FEATURE_FILE: 'data/v2/hb_test_feature.csv'
MODEL:
  POOLING: "avg_pool"
  RESIDUAL: True
  KERNELS: 64
DATA_LOADER:
  NUM_WORKERS: 2
SAVE_JOINT_PROB: True